### ISSUE TITLE
Larger Levels

### ISSUE THREAD

**Issue by teeks99** [Sesu8642/FeudalTactics#6]
The S-M-L map sizes are good, but some larger options would be even better. 

Another more general option would be to give the player the ability to pick the number of spaces they want to play with.

**Comment by Sesu8642** [comment]
Some concerns:
- the game should be performant even on older hardware and large maps could be problematic
- not sure if huge maps are fun because at some point you might become overpowered and then still need to conquer large parts of the map without any challenge

These two things need to be tested but I'm not against it.

**Comment by Sesu8642** [comment]
PR from @teeks99 : #10

**Comment by Sesu8642** [comment]
I tested the changes you did in your PR. I think that the large maps can be fun indeed. However, i noticed some slowdowns when playing the game.

Older Android phone:
Almost every action has a slight delay. This is noticeable on XL and gets even worse on XXL. But it doesn't seem to get much worse over time.

PC:
No slowdown at the beginning of the turn but it gets worse and worse the more actions you do. The thing that causes the slowdown is autosaving, specifically writing to disk (I shouldn't have bought the cheapest SSD... :x ).

It seems like libGDXs preferences mechanism that i use for saving is more optimized on Android than on PC.

Anyway, this is not acceptable as is. Some ideas on how to improve the situation:
- reduce the maximum number of undos
- reduce savegame json size by using short key names (makes it less readable)
- autosave asynchronously
- autosave less often
- save only what changed from the last autosave instead of the whole game state
- save data as binary instead of json

I think that the first 3 or 4 ideas make the most sense.

**Comment by Sesu8642** [comment]
I tried shorter field names which reduces the size of a file with a single autosave (small map) from 4,5 to 3,3 kb. Using Kryo and writing base64 to the preferences reduces the size to about 50%. The proper solution is probably to use Kryo and write the binary to a file. But that's a little more complicated than using LibGDX's preferences.
I will merge merge your PR an deal with this separately.

**Comment by Sesu8642** [comment]
I disabled the xxlarge option because I don't want to delay the next update any further but I will try to find a solution for the next one.
