### ISSUE TITLE
Cannot combine two spearmen

### ISSUE THREAD

**Issue by mwadle** [Sesu8642/FeudalTactics#77]
In the current implementation, two spearmen cannot be combined into a baron. Combining units only works if a peasant is one of the units being combined.

I assumed this was intentionally done to stay true to the original slay game. Although the tutorial only explicitly mentions peasants can be combined with other units, after some testing it seems two spearmen can be combined in the original game.

**Comment by Sesu8642** [comment]
Interesting observation. Which version of slay are you testing with? I assumed it wouldn't be possible until now.
I already considered implementing this since it was requested a few times. And since the original allows it, I don't see any reason not to allow it in Feudal Tactics.
What about spearman + knight? Your PR would allow it. Does Slay allow it too?

**Comment by Sesu8642** [comment]
Just realized the spearman + knight part doesnt make much sense since spearman + spearman already gives you a baron.

**Comment by mwadle** [comment]
I tested it on the trial windows desktop version and the google play store version, both allowed it.

Neither slay nor the PR should allow you to combine a spearman with a knight XD
